# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "75dabda94715b82d25167321fa6fc848"
name = "pitest"
application_url = "https://www.adaiwiz.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://www.adaiwiz.com/auth/callback",
  "https://www.adaiwiz.com/auth/shopify/callback",
  "https://www.adaiwiz.com/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
